<a href="https://colab.research.google.com/github/navneetslovely/Wifi_RSSI_localization/blob/main/RSSI_DT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression

In [4]:
fetch_training_sample= '/content/drive/My Drive/UJIndoorLoc/UJIndoorLoc/trainingData.csv'
fetch_validation_sample= '/content/drive/My Drive/UJIndoorLoc/UJIndoorLoc/validationData.csv'
training_data = pd.read_csv(fetch_training_sample)
validation_data = pd.read_csv(fetch_validation_sample)
df= pd.DataFrame(data=training_data)
df1 = pd.DataFrame(data=validation_data)
df['BUILDINGID']=df.BUILDINGID.astype(str)
df1['BUILDINGID']=df.BUILDINGID.astype(str)
df['FLOOR']=df.FLOOR.astype(str)
df1['FLOOR']=df.FLOOR.astype(str)
df['newfeature'] = df[['BUILDINGID', 'FLOOR']].apply(lambda x: '.'.join(x), axis=1)
df[['newfeature']] = df[['newfeature']].apply(pd.to_numeric) 
df1['newfeature'] = df[['BUILDINGID', 'FLOOR']].apply(lambda x: '.'.join(x), axis=1)
df1[['newfeature']] = df1[['newfeature']].apply(pd.to_numeric) 
modified_training_data = pd.concat([df,df1], ignore_index=True)
modified_training_data['newfeature']=1000*modified_training_data['newfeature']
modified_training_data['newfeature'] = modified_training_data['newfeature'].astype(int) 

x_modified_training_data = modified_training_data.drop(columns=['LONGITUDE',"LATITUDE", "FLOOR", "BUILDINGID", "SPACEID", "RELATIVEPOSITION", "USERID", "PHONEID", "TIMESTAMP", "newfeature"])
y_modified_training_data = modified_training_data.loc[:,['LONGITUDE',"LATITUDE", "FLOOR", "BUILDINGID", "SPACEID","newfeature"]]

In [5]:
X_train, X_test, Y_train, Y_test = train_test_split(x_modified_training_data,y_modified_training_data, test_size= 0.33,random_state=42)
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [6]:
error_newfeature = []
error = []
error_building = []

classifier = LogisticRegression(random_state=0)
classifier.fit(X_train, Y_train['newfeature'])
y_pred = classifier.predict(X_test)
y_pred_pro=classifier.predict_proba(X_test)
y_pred_score=classifier.score(X_test,Y_test['newfeature'])
print(y_pred_pro)
print(y_pred_score)
print(confusion_matrix(Y_test['newfeature'], y_pred),"new combined feature \n")
print(classification_report(Y_test['newfeature'], y_pred),"new combined feature \n")

[[1.30551293e-03 9.98640686e-01 7.03614090e-06 ... 9.03773516e-11
  8.14064793e-09 2.51662466e-06]
 [2.79023977e-08 6.71947889e-10 6.21303889e-10 ... 1.28967126e-10
  9.40931821e-01 1.15151510e-04]
 [9.80939398e-12 2.43210167e-11 2.71090585e-11 ... 1.20654463e-11
  1.63557789e-12 9.96182187e-15]
 ...
 [5.36997226e-23 1.92502591e-25 9.99999999e-01 ... 1.52953049e-26
  1.46098284e-39 8.29569785e-21]
 [1.07471549e-06 3.33501450e-08 4.50175864e-08 ... 6.65737541e-04
  4.04954128e-05 8.20554026e-10]
 [6.62490782e-06 3.51781939e-07 6.53735875e-07 ... 3.98950697e-05
  9.99350709e-01 4.37815892e-04]]
0.9067088972070256
[[335  21   0   0   0   0   0   0   0   0   0   2   0]
 [ 27 387  11   0   0   0   4   0   0   0   0   9   0]
 [  0   8 425  35   0   1   3   0   0   0   0   7   0]
 [  0   1  30 440   0   0   0   0   0   0   0   4   0]
 [  0   0   0   0 434  17   3   0   0   0   0   0   0]
 [  0   0   0   0  26 444  14   0   0   0   0   3   0]
 [  5   9   7   6   8  12 472   8   4   3   1  45  

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [7]:
from sklearn import svm
classifier = svm.SVC()
classifier.fit(X_train, Y_train['newfeature'])
y_pred = classifier.predict(X_test)
print(confusion_matrix(Y_test['newfeature'], y_pred),"new combined feature \n")
print(classification_report(Y_test['newfeature'], y_pred),"new combined feature \n")

[[344  13   0   0   0   0   0   0   0   0   0   1   0]
 [ 18 407   4   1   0   0   0   0   0   0   0   8   0]
 [  0   1 426  34   0   0   0   0   0   0   0  18   0]
 [  0   1  17 448   0   0   0   0   0   0   0   9   0]
 [  0   0   0   0 433  19   0   0   2   0   0   0   0]
 [  0   0   0   0  14 469   3   0   0   0   0   1   0]
 [  6  11   7   5   4  15 471  14   4   4   1  39   1]
 [  0   0   0   0   0   0  18 284  16   0   0   0   0]
 [  0   0   0   0   0   0   0   0 614  13   0   0   0]
 [  0   0   0   0   0   0   0   0   9 700  12  15   0]
 [  0   0   0   0   0   0   0   0   0  14 481  17   0]
 [  5  16  11  12   1  14  40   6   2   5   1 988   4]
 [  1   0   0   0   0   0   0   0   0   0   0  26 348]] new combined feature 

              precision    recall  f1-score   support

           0       0.92      0.96      0.94       358
         100       0.91      0.93      0.92       438
         200       0.92      0.89      0.90       479
         300       0.90      0.94      0.92 

In [8]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(max_depth=2)
classifier.fit(X_train, Y_train['newfeature'])
y_pred = classifier.predict(X_test)
y_pred_pro=classifier.predict_proba(X_test)
print(y_pred_pro)
print(confusion_matrix(Y_test['newfeature'], y_pred),"new combined feature \n")
print(classification_report(Y_test['newfeature'], y_pred),"new combined feature \n")


classifier.fit(X_train, Y_train['FLOOR'])
y_pred = classifier.predict(X_test)
y_pred_pro=classifier.predict_proba(X_test)
print(y_pred_pro)
print(confusion_matrix(Y_test['FLOOR'], y_pred),"new combined feature \n")
print(classification_report(Y_test['FLOOR'], y_pred),"new combined feature \n")

[[0.06803644 0.08897073 0.09342896 ... 0.04274084 0.08993991 0.05902307]
 [0.         0.         0.         ... 0.05932203 0.10653753 0.01331719]
 [0.         0.         0.         ... 0.00248756 0.00995025 0.        ]
 ...
 [0.06803644 0.08897073 0.09342896 ... 0.04274084 0.08993991 0.05902307]
 [0.         0.         0.         ... 0.26648097 0.55663881 0.05803157]
 [0.         0.         0.         ... 0.26648097 0.55663881 0.05803157]]
[[  0   0   0   0   0   0 358   0   0   0   0   0   0]
 [  0   0   0   0   0   0 438   0   0   0   0   0   0]
 [  0   0   0   0   0   0 479   0   0   0   0   0   0]
 [  0   0   0   0   0   0 475   0   0   0   0   0   0]
 [  0   0   0   0   0   0 454   0   0   0   0   0   0]
 [  0   0   0   0   0   0 487   0   0   0   0   0   0]
 [  0   0   0   0   0   0 558   0   5   8   0  11   0]
 [  0   0   0   0   0   0 318   0   0   0   0   0   0]
 [  0   0   0   0   0   0 185   0 317 115   0  10   0]
 [  0   0   0   0   0   0 351   0  45 225   0 115   0]
 [  0 

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[[ 421    0 1002   16    0]
 [ 240    0 1368   53    0]
 [  33    0 1372  159    9]
 [  13    0 1369  500   16]
 [   1    0   94   77  203]] new combined feature 

              precision    recall  f1-score   support

           0       0.59      0.29      0.39      1439
           1       0.00      0.00      0.00      1661
           2       0.26      0.87      0.40      1573
           3       0.62      0.26      0.37      1898
           4       0.89      0.54      0.67       375

    accuracy                           0.36      6946
   macro avg       0.47      0.39      0.37      6946
weighted avg       0.40      0.36      0.31      6946
 new combined feature 



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [9]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC

log_clf = LogisticRegression()
rnd_clf = RandomForestClassifier()
svm_clf = SVC()

voting_clf = VotingClassifier(estimators=[('lr', log_clf), ('rf', rnd_clf), ('svc',svm_clf)],
                              voting= 'hard')
voting_clf.fit(X_train,Y_train['newfeature'])
for clf in (log_clf,rnd_clf, svm_clf,voting_clf):
    clf.fit(X_train,Y_train['newfeature'])
    y_pred= clf.predict(X_test)
    print(accuracy_score(Y_test['newfeature'],y_pred))
    print("***********************************")
    print(confusion_matrix(Y_test['newfeature'], y_pred),"new combined feature \n")
    print(classification_report(Y_test['newfeature'], y_pred),"new combined feature \n")

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


0.9067088972070256
***********************************
[[335  21   0   0   0   0   0   0   0   0   0   2   0]
 [ 27 387  11   0   0   0   4   0   0   0   0   9   0]
 [  0   8 425  35   0   1   3   0   0   0   0   7   0]
 [  0   1  30 440   0   0   0   0   0   0   0   4   0]
 [  0   0   0   0 434  17   3   0   0   0   0   0   0]
 [  0   0   0   0  26 444  14   0   0   0   0   3   0]
 [  5   9   7   6   8  12 472   8   4   3   1  45   2]
 [  0   0   0   0   0   0  16 301   0   0   0   1   0]
 [  0   0   0   0   0   0   0  11 599  17   0   0   0]
 [  0   0   0   0   0   5   2   0  19 691  17   2   0]
 [  0   0   0   0   0   0   1   0   0  21 471  19   0]
 [  6   6   8  11   1  15  60   8   1   9  12 953  15]
 [  0   0   0   0   0   0   0   0   0   0   0  29 346]] new combined feature 

              precision    recall  f1-score   support

           0       0.90      0.94      0.92       358
         100       0.90      0.88      0.89       438
         200       0.88      0.89      0.89

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


0.9380938669737978
***********************************
[[349   9   0   0   0   0   0   0   0   0   0   0   0]
 [ 17 415   5   0   0   0   0   0   0   0   0   1   0]
 [  0   4 450  25   0   0   0   0   0   0   0   0   0]
 [  0   1  11 463   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0 444  10   0   0   0   0   0   0   0]
 [  0   0   0   0  12 474   1   0   0   0   0   0   0]
 [  7  13  10   9   6  12 480  10   4   3   1  27   0]
 [  0   0   0   0   0   0  13 289  16   0   0   0   0]
 [  0   0   0   0   0   0   0   0 616  11   0   0   0]
 [  0   0   0   0   0   0   1   0   8 718   9   0   0]
 [  0   0   0   0   0   0   1   0   0  11 492   8   0]
 [  5  18  22  15   1  18  36   6   2   4   1 973   4]
 [  1   0   0   0   0   0   0   0   0   0   0  21 353]] new combined feature 

              precision    recall  f1-score   support

           0       0.92      0.97      0.95       358
         100       0.90      0.95      0.92       438
         200       0.90      0.94      0.92

In [10]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
bag_clf = BaggingClassifier(DecisionTreeClassifier(), n_estimators=500,max_samples=100, bootstrap=True, n_jobs=-1)
bag_clf.fit(X_train,Y_train['newfeature'])
y_pred= bag_clf.predict(X_test)
y_pred_pro= bag_clf.predict_proba(X_test)

print("***********************************")
print(confusion_matrix(Y_test['newfeature'], y_pred),"new combined feature \n")
print(classification_report(Y_test['newfeature'], y_pred),"new combined feature \n")
print("***********************************")


***********************************
[[305  50   0   0   0   0   3   0   0   0   0   0   0]
 [ 24 398  12   4   0   0   0   0   0   0   0   0   0]
 [  6  17 425  29   0   0   2   0   0   0   0   0   0]
 [  0   0   1 474   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0 361  67  26   0   0   0   0   0   0]
 [  0   0   0   0 103 350  34   0   0   0   0   0   0]
 [  3  25  20  12  10  79 382  13   6  19   3   9   1]
 [  0   0   0   0   0  17 129 170   0   0   0   2   0]
 [  0   0   0   0   1   0  11   0 604   7   0   4   0]
 [  0   0   0   0   0   0   0   0  34 662   5  35   0]
 [  0   0   0   0   0   0   3   0   0  28 386  95   0]
 [ 16  36  26  24   6  17  38   6   3  16   9 905   3]
 [  1   0   0   0   0   0   0   0   1   1   0 125 247]] new combined feature 

              precision    recall  f1-score   support

           0       0.86      0.85      0.86       358
         100       0.76      0.91      0.83       438
         200       0.88      0.89      0.88       479
        

In [11]:
accuracy_score(Y_test['newfeature'], y_pred)

0.816153181687302

In [17]:
rnd_clf= RandomForestClassifier(n_estimators=500,max_leaf_nodes=20,n_jobs=-1)
rnd_clf.fit(X_train,Y_train['newfeature'])
y_pred_rf= rnd_clf.predict(X_test)

In [18]:
print(confusion_matrix(Y_test['newfeature'], y_pred_rf),"new combined feature \n")
print(classification_report(Y_test['newfeature'], y_pred_rf),"new combined feature \n")

[[211 143   1   0   0   0   3   0   0   0   0   0   0]
 [  7 410  20   1   0   0   0   0   0   0   0   0   0]
 [  0  38 232 201   0   0   8   0   0   0   0   0   0]
 [  0   0   2 473   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0 334  95  25   0   0   0   0   0   0]
 [  0   0   0   0 114 332  41   0   0   0   0   0   0]
 [  2  30   7  20  22 109 342   3   7  16   2  22   0]
 [  0   0   0   0   0  25 174 108   0   0   0  11   0]
 [  0   0   0   0   1   0  11   0 602   8   0   5   0]
 [  0   0   0   0   0   0   0   0  43 635   1  57   0]
 [  0   0   0   0   0   0   6   0   0  34 298 174   0]
 [ 12  41  11  35   8  17  41   4   3  14   4 914   1]
 [  1   0   0   0   0   0   0   0   0   0   0 179 195]] new combined feature 

              precision    recall  f1-score   support

           0       0.91      0.59      0.71       358
         100       0.62      0.94      0.75       438
         200       0.85      0.48      0.62       479
         300       0.65      1.00      0.79 

In [19]:
bag_clf = BaggingClassifier(DecisionTreeClassifier(max_features= 'auto', max_leaf_nodes= 16), n_estimators= 500, max_samples=1, bootstrap=True, n_jobs=-1)
bag_clf.fit(X_train,Y_train['newfeature'])
y_pred= bag_clf.predict(X_test)

In [20]:
print(confusion_matrix(Y_test['newfeature'], y_pred),"new combined feature \n")
print(classification_report(Y_test['newfeature'], y_pred),"new combined feature \n")

[[   0    0    0    0    0    0    0    0    0    0    0  358    0]
 [   0    0    0    0    0    0    0    0    0    0    0  438    0]
 [   0    0    0    0    0    0    0    0    0    0    0  479    0]
 [   0    0    0    0    0    0    0    0    0    0    0  475    0]
 [   0    0    0    0    0    0    0    0    0    0    0  454    0]
 [   0    0    0    0    0    0    0    0    0    0    0  487    0]
 [   0    0    0    0    0    0    0    0    0    0    0  582    0]
 [   0    0    0    0    0    0    0    0    0    0    0  318    0]
 [   0    0    0    0    0    0    0    0    0    0    0  627    0]
 [   0    0    0    0    0    0    0    0    0    0    0  736    0]
 [   0    0    0    0    0    0    0    0    0    0    0  512    0]
 [   0    0    0    0    0    0    0    0    0    0    0 1105    0]
 [   0    0    0    0    0    0    0    0    0    0    0  375    0]] new combined feature 

              precision    recall  f1-score   support

           0       0.00      0.00    

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
