<a href="https://colab.research.google.com/github/navneetslovely/Wifi_RSSI_localization/blob/main/RSSI_DT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression

In [18]:
fetch_training_sample= '/content/drive/My Drive/UJIndoorLoc/UJIndoorLoc/trainingData.csv'
fetch_validation_sample= '/content/drive/My Drive/UJIndoorLoc/UJIndoorLoc/validationData.csv'
training_data = pd.read_csv(fetch_training_sample)
validation_data = pd.read_csv(fetch_validation_sample)
df= pd.DataFrame(data=training_data)
df1 = pd.DataFrame(data=validation_data)
df['BUILDINGID']=df.BUILDINGID.astype(str)
df1['BUILDINGID']=df.BUILDINGID.astype(str)
df['FLOOR']=df.FLOOR.astype(str)
df1['FLOOR']=df.FLOOR.astype(str)
df['newfeature'] = df[['BUILDINGID', 'FLOOR']].apply(lambda x: '.'.join(x), axis=1)
df[['newfeature']] = df[['newfeature']].apply(pd.to_numeric) 
df1['newfeature'] = df[['BUILDINGID', 'FLOOR']].apply(lambda x: '.'.join(x), axis=1)
df1[['newfeature']] = df1[['newfeature']].apply(pd.to_numeric) 
modified_training_data = pd.concat([df,df1], ignore_index=True)
modified_training_data['newfeature']=1000*modified_training_data['newfeature']
modified_training_data['newfeature'] = modified_training_data['newfeature'].astype(int) 

x_modified_training_data = modified_training_data.drop(columns=['LONGITUDE',"LATITUDE", "FLOOR", "BUILDINGID", "SPACEID", "RELATIVEPOSITION", "USERID", "PHONEID", "TIMESTAMP", "newfeature"])
y_modified_training_data = modified_training_data.loc[:,['LONGITUDE',"LATITUDE", "FLOOR", "BUILDINGID", "SPACEID","newfeature"]]

In [19]:
X_train, X_test, Y_train, Y_test = train_test_split(x_modified_training_data,y_modified_training_data, test_size= 0.33,random_state=42)
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [22]:
error_newfeature = []
error = []
error_building = []

classifier = LogisticRegression(random_state=0)
classifier.fit(X_train, Y_train['newfeature'])
y_pred = classifier.predict(X_test)
y_pred_pro=classifier.predict_proba(X_test)
y_pred_score=classifier.score(X_test,Y_test['newfeature'])
print(y_pred_pro)
print(y_pred_score)
print(confusion_matrix(Y_test['newfeature'], y_pred),"new combined feature \n")
print(classification_report(Y_test['newfeature'], y_pred),"new combined feature \n")

[[1.30551202e-03 9.98640687e-01 7.03613843e-06 ... 9.03772850e-11
  8.14064232e-09 2.51662322e-06]
 [2.79024151e-08 6.71948245e-10 6.21304318e-10 ... 1.28967275e-10
  9.40931846e-01 1.15151581e-04]
 [9.80938918e-12 2.43210025e-11 2.71090482e-11 ... 1.20654428e-11
  1.63557768e-12 9.96181933e-15]
 ...
 [5.36997578e-23 1.92502559e-25 9.99999999e-01 ... 1.52953063e-26
  1.46098347e-39 8.29569716e-21]
 [1.07471499e-06 3.33501277e-08 4.50175691e-08 ... 6.65737380e-04
  4.04954107e-05 8.20553698e-10]
 [6.62490760e-06 3.51781892e-07 6.53735859e-07 ... 3.98950683e-05
  9.99350709e-01 4.37815923e-04]]
0.9067088972070256
[[335  21   0   0   0   0   0   0   0   0   0   2   0]
 [ 27 387  11   0   0   0   4   0   0   0   0   9   0]
 [  0   8 425  35   0   1   3   0   0   0   0   7   0]
 [  0   1  30 440   0   0   0   0   0   0   0   4   0]
 [  0   0   0   0 434  17   3   0   0   0   0   0   0]
 [  0   0   0   0  26 444  14   0   0   0   0   3   0]
 [  5   9   7   6   8  12 472   8   4   3   1  45  

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [26]:
from sklearn import svm
classifier = svm.SVC()
classifier.fit(X_train, Y_train['newfeature'])
y_pred = classifier.predict(X_test)
print(confusion_matrix(Y_test['newfeature'], y_pred),"new combined feature \n")
print(classification_report(Y_test['newfeature'], y_pred),"new combined feature \n")

[[344  13   0   0   0   0   0   0   0   0   0   1   0]
 [ 18 407   4   1   0   0   0   0   0   0   0   8   0]
 [  0   1 426  34   0   0   0   0   0   0   0  18   0]
 [  0   1  17 448   0   0   0   0   0   0   0   9   0]
 [  0   0   0   0 433  19   0   0   2   0   0   0   0]
 [  0   0   0   0  14 469   3   0   0   0   0   1   0]
 [  6  11   7   5   4  15 471  14   4   4   1  39   1]
 [  0   0   0   0   0   0  18 284  16   0   0   0   0]
 [  0   0   0   0   0   0   0   0 614  13   0   0   0]
 [  0   0   0   0   0   0   0   0   9 700  12  15   0]
 [  0   0   0   0   0   0   0   0   0  14 481  17   0]
 [  5  16  11  12   1  14  40   6   2   5   1 988   4]
 [  1   0   0   0   0   0   0   0   0   0   0  26 348]] new combined feature 

              precision    recall  f1-score   support

           0       0.92      0.96      0.94       358
         100       0.91      0.93      0.92       438
         200       0.92      0.89      0.90       479
         300       0.90      0.94      0.92 

In [36]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(max_depth=2)
classifier.fit(X_train, Y_train['newfeature'])
y_pred = classifier.predict(X_test)
y_pred_pro=classifier.predict_proba(X_test)
print(y_pred_pro)
print(confusion_matrix(Y_test['newfeature'], y_pred),"new combined feature \n")
print(classification_report(Y_test['newfeature'], y_pred),"new combined feature \n")


classifier.fit(X_train, Y_train['FLOOR'])
y_pred = classifier.predict(X_test)
y_pred_pro=classifier.predict_proba(X_test)
print(y_pred_pro)
print(confusion_matrix(Y_test['FLOOR'], y_pred),"new combined feature \n")
print(classification_report(Y_test['FLOOR'], y_pred),"new combined feature \n")

[[0.06803644 0.08897073 0.09342896 ... 0.04274084 0.08993991 0.05902307]
 [0.         0.         0.         ... 0.05932203 0.10653753 0.01331719]
 [0.         0.         0.         ... 0.00248756 0.00995025 0.        ]
 ...
 [0.06803644 0.08897073 0.09342896 ... 0.04274084 0.08993991 0.05902307]
 [0.         0.         0.         ... 0.26648097 0.55663881 0.05803157]
 [0.         0.         0.         ... 0.26648097 0.55663881 0.05803157]]
[[  0   0   0   0   0   0 358   0   0   0   0   0   0]
 [  0   0   0   0   0   0 438   0   0   0   0   0   0]
 [  0   0   0   0   0   0 479   0   0   0   0   0   0]
 [  0   0   0   0   0   0 475   0   0   0   0   0   0]
 [  0   0   0   0   0   0 454   0   0   0   0   0   0]
 [  0   0   0   0   0   0 487   0   0   0   0   0   0]
 [  0   0   0   0   0   0 558   0   5   8   0  11   0]
 [  0   0   0   0   0   0 318   0   0   0   0   0   0]
 [  0   0   0   0   0   0 185   0 317 115   0  10   0]
 [  0   0   0   0   0   0 351   0  45 225   0 115   0]
 [  0 

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

           0       0.59      0.29      0.39      1439
           1       0.00      0.00      0.00      1661
           2       0.26      0.87      0.40      1573
           3       0.62      0.26      0.37      1898
           4       0.89      0.54      0.67       375

    accuracy                           0.36      6946
   macro avg       0.47      0.39      0.37      6946
weighted avg       0.40      0.36      0.31      6946
 new combined feature 



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [54]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC

log_clf = LogisticRegression()
rnd_clf = RandomForestClassifier()
svm_clf = SVC()

voting_clf = VotingClassifier(estimators=[('lr', log_clf), ('rf', rnd_clf), ('svc',svm_clf)],
                              voting= 'hard')
voting_clf.fit(X_train,Y_train['newfeature'])
for clf in (log_clf,rnd_clf, svm_clf,voting_clf):
    clf.fit(X_train,Y_train['newfeature'])
    y_pred= clf.predict(X_test)
    print(accuracy_score(Y_test['newfeature'],y_pred))
    print("***********************************")
    print(confusion_matrix(Y_test['newfeature'], y_pred),"new combined feature \n")
    print(classification_report(Y_test['newfeature'], y_pred),"new combined feature \n")

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


0.9067088972070256
***********************************
[[335  21   0   0   0   0   0   0   0   0   0   2   0]
 [ 27 387  11   0   0   0   4   0   0   0   0   9   0]
 [  0   8 425  35   0   1   3   0   0   0   0   7   0]
 [  0   1  30 440   0   0   0   0   0   0   0   4   0]
 [  0   0   0   0 434  17   3   0   0   0   0   0   0]
 [  0   0   0   0  26 444  14   0   0   0   0   3   0]
 [  5   9   7   6   8  12 472   8   4   3   1  45   2]
 [  0   0   0   0   0   0  16 301   0   0   0   1   0]
 [  0   0   0   0   0   0   0  11 599  17   0   0   0]
 [  0   0   0   0   0   5   2   0  19 691  17   2   0]
 [  0   0   0   0   0   0   1   0   0  21 471  19   0]
 [  6   6   8  11   1  15  60   8   1   9  12 953  15]
 [  0   0   0   0   0   0   0   0   0   0   0  29 346]] new combined feature 

              precision    recall  f1-score   support

           0       0.90      0.94      0.92       358
         100       0.90      0.88      0.89       438
         200       0.88      0.89      0.89

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


0.9369421249640081
***********************************
[[349   9   0   0   0   0   0   0   0   0   0   0   0]
 [ 17 415   5   0   0   0   0   0   0   0   0   1   0]
 [  0   4 450  25   0   0   0   0   0   0   0   0   0]
 [  0   1  11 463   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0 444  10   0   0   0   0   0   0   0]
 [  0   0   0   0  13 473   1   0   0   0   0   0   0]
 [  7  13  10   9   6  12 477  10   4   4   1  28   1]
 [  0   0   0   0   0   0  14 288  16   0   0   0   0]
 [  0   0   0   0   0   0   0   0 616  11   0   0   0]
 [  0   0   0   0   0   0   0   0   9 718   9   0   0]
 [  0   0   0   0   0   0   1   0   0  11 492   8   0]
 [  5  17  22  15   1  19  39   6   2   4   1 970   4]
 [  1   0   0   0   0   0   0   0   0   0   0  21 353]] new combined feature 

              precision    recall  f1-score   support

           0       0.92      0.97      0.95       358
         100       0.90      0.95      0.93       438
         200       0.90      0.94      0.92

In [47]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
bag_clf = BaggingClassifier(DecisionTreeClassifier(), n_estimators=500,max_samples=100, bootstrap=True, n_jobs=-1)
bag_clf.fit(X_train,Y_train['newfeature'])
y_pred= bag_clf.predict(X_test)
y_pred_pro= bag_clf.predict_proba(X_test)

print("***********************************")
print(confusion_matrix(Y_test['newfeature'], y_pred),"new combined feature \n")
print(classification_report(Y_test['newfeature'], y_pred),"new combined feature \n")
print("***********************************")


***********************************
[[317  37   0   0   0   0   3   0   0   0   0   1   0]
 [ 22 397  18   1   0   0   0   0   0   0   0   0   0]
 [  6  17 414  38   0   0   4   0   0   0   0   0   0]
 [  0   0   8 467   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0 373  54  27   0   0   0   0   0   0]
 [  0   0   0   0  98 356  33   0   0   0   0   0   0]
 [  3  26  16  14  12  82 382   9   6  17   6   9   0]
 [  0   0   0   0   0  17  98 203   0   0   0   0   0]
 [  0   0   0   0   2   0  11   0 608   3   0   3   0]
 [  0   0   0   0   0   0   0   0  53 649   9  25   0]
 [  0   0   0   0   0   0   0   0   0  20 407  85   0]
 [ 13  38  24  26   6  17  37   7   4  13  11 908   1]
 [  1   0   0   0   0   0   0   0   1   1   0 124 248]] new combined feature 

              precision    recall  f1-score   support

           0       0.88      0.89      0.88       358
         100       0.77      0.91      0.83       438
         200       0.86      0.86      0.86       479
        

In [52]:
accuracy_score(Y_test['newfeature'], y_pred)

0.8247912467607256

In [55]:
rnd_clf= RandomForestClassifier(n_estimators=500,max_leaf_nodes=20,n_jobs=-1)
rnd_clf.fit(X_train,Y_train['newfeature'])
y_pred_rf= rnd_clf.predict(X_test)

In [56]:
print(confusion_matrix(Y_test['newfeature'], y_pred),"new combined feature \n")
print(classification_report(Y_test['newfeature'], y_pred),"new combined feature \n")

[[349   9   0   0   0   0   0   0   0   0   0   0   0]
 [ 17 415   5   0   0   0   0   0   0   0   0   1   0]
 [  0   4 450  25   0   0   0   0   0   0   0   0   0]
 [  0   1  11 463   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0 444  10   0   0   0   0   0   0   0]
 [  0   0   0   0  13 473   1   0   0   0   0   0   0]
 [  7  13  10   9   6  12 477  10   4   4   1  28   1]
 [  0   0   0   0   0   0  14 288  16   0   0   0   0]
 [  0   0   0   0   0   0   0   0 616  11   0   0   0]
 [  0   0   0   0   0   0   0   0   9 718   9   0   0]
 [  0   0   0   0   0   0   1   0   0  11 492   8   0]
 [  5  17  22  15   1  19  39   6   2   4   1 970   4]
 [  1   0   0   0   0   0   0   0   0   0   0  21 353]] new combined feature 

              precision    recall  f1-score   support

           0       0.92      0.97      0.95       358
         100       0.90      0.95      0.93       438
         200       0.90      0.94      0.92       479
         300       0.90      0.97      0.94 